[mypy]
files=**/*.py
plugins = sqlmypy

[mypy-rdkit.*]
ignore_missing_imports = True

[mypy-obonet]
ignore_missing_imports = True

[mypy-networkx]
ignore_missing_imports = True

[mypy-pybiopax]
ignore_missing_imports = True
