app = "brainshare-backend-worker"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sjc"

[build]
dockerfile = "Dockerfile.worker"

[experimental]
auto_rollback = true

[[vm]]
size = "shared-cpu-2x"
