[tool.black]
line-length = 100

[tool.poetry]
name = "backend"
version = "0.2.0"
description = ""
authors = ["Zachary King <zaking17@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
celery = { extras = ["redis"], version = "^5.4.0" }
fastapi = "^0.110.2"
sqlalchemy = { extras = ["asyncio", "mypy"], version = "^2.0.29" }
uvicorn = { extras = ["standard"], version = "^0.29.0" }
pytz = "^2024.1"

[tool.poetry.group.testing.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"

[tool.poetry.group.dev.dependencies]
black = "^24.4.1"
celery-types = "^0.22.0"
psycopg2-binary = "^2.9.6"      # for codegen
types-redis = "^4.6.0.20240425"
#
sqlacodegen = { git = "https://github.com/agronholm/sqlacodegen", branch = "master" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
