// This file is auto-generated by @hey-api/openapi-ts

export const $AppToDeploy = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        clean_up_only: {
            type: 'boolean',
            title: 'Clean Up Only',
            default: false
        }
    },
    type: 'object',
    required: ['id'],
    title: 'AppToDeploy'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;