// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetHealthHealthGetResponse, PostTaskDeployAppTaskDeployAppPostData, PostTaskDeployAppTaskDeployAppPostResponse } from './types.gen';

/**
 * Get Health
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const getHealthHealthGet = (): CancelablePromise<GetHealthHealthGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/health'
}); };

/**
 * Post Task Deploy App
 * Clean up any existing tasks and start a new one
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const postTaskDeployAppTaskDeployAppPost = (data: PostTaskDeployAppTaskDeployAppPostData): CancelablePromise<PostTaskDeployAppTaskDeployAppPostResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/task/deploy-app',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };