// This file is auto-generated by @hey-api/openapi-ts

export type WidgetSuggestion = {
    name: string;
    description: string;
    vegaLiteSpec: unknown;
};

export type GetHealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSuggestWidgetSuggestWidgetGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/suggest/widget';
};

export type GetSuggestWidgetSuggestWidgetGetResponses = {
    /**
     * Successful Response
     */
    200: WidgetSuggestion;
};

export type GetSuggestWidgetSuggestWidgetGetResponse = GetSuggestWidgetSuggestWidgetGetResponses[keyof GetSuggestWidgetSuggestWidgetGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};