CREATE TABLE tool(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  user_id uuid NOT NULL,
  UNIQUE (name, user_id)
);

ALTER TABLE tool ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated user can manage their tools" ON tool
  FOR ALL TO authenticated
    USING (auth.uid() = user_id);

