create table "public"."file" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "size" bigint not null,
    "bucket_id" text not null,
    "object_path" text not null,
    "user_id" uuid not null
);


alter table "public"."file" enable row level security;

CREATE UNIQUE INDEX file_pkey ON public.file USING btree (id);

alter table "public"."file" add constraint "file_pkey" PRIMARY KEY using index "file_pkey";

alter table "public"."file" add constraint "file_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."file" validate constraint "file_user_id_fkey";

create policy "Authenticated user can manage their files"
on "public"."file"
as permissive
for all
to public
using ((auth.uid() = user_id));



drop policy "Anyone can read objects" on "storage"."objects";

create policy "Authenticated user can create files"
on "storage"."objects"
as permissive
for insert
to authenticated
with check ((bucket_id = 'files'::text));


create policy "Authenticated user can manage their own files"
on "storage"."objects"
as permissive
for all
to public
using (((bucket_id = 'files'::text) AND (auth.uid() = owner)));


-- Use Postgres to create a bucket.

insert into storage.buckets (id, name) values ('files', 'files');
