create table "public"."genome_history" (
    "id" bigint generated by default as identity not null,
    "time" timestamp without time zone,
    "genome_id" bigint not null,
    "source" text not null,
    "source_details" text not null,
    "user_id" uuid,
    "change_type" text not null,
    "change_column" text
);


alter table "public"."genome_history" enable row level security;

create table "public"."protein_history" (
    "id" bigint generated by default as identity not null,
    "time" timestamp without time zone,
    "protein_id" bigint not null,
    "source" text not null,
    "source_details" text not null,
    "user_id" uuid,
    "change_type" text not null,
    "change_column" text
);


alter table "public"."protein_history" enable row level security;

create table "public"."reaction_history" (
    "id" bigint generated by default as identity not null,
    "time" timestamp without time zone,
    "reaction_id" bigint not null,
    "source" text not null,
    "source_details" text not null,
    "user_id" uuid,
    "change_type" text not null,
    "change_column" text
);


alter table "public"."reaction_history" enable row level security;

create table "public"."species_history" (
    "id" bigint generated by default as identity not null,
    "time" timestamp without time zone,
    "species_id" bigint not null,
    "source" text not null,
    "source_details" text not null,
    "user_id" uuid,
    "change_type" text not null,
    "change_column" text
);


alter table "public"."species_history" enable row level security;

CREATE UNIQUE INDEX genome_history_pkey ON public.genome_history USING btree (id);

CREATE UNIQUE INDEX protein_history_pkey ON public.protein_history USING btree (id);

CREATE UNIQUE INDEX reaction_history_pkey ON public.reaction_history USING btree (id);

CREATE UNIQUE INDEX species_history_pkey ON public.species_history USING btree (id);

alter table "public"."genome_history" add constraint "genome_history_pkey" PRIMARY KEY using index "genome_history_pkey";

alter table "public"."protein_history" add constraint "protein_history_pkey" PRIMARY KEY using index "protein_history_pkey";

alter table "public"."reaction_history" add constraint "reaction_history_pkey" PRIMARY KEY using index "reaction_history_pkey";

alter table "public"."species_history" add constraint "species_history_pkey" PRIMARY KEY using index "species_history_pkey";

alter table "public"."genome_history" add constraint "genome_history_change_type_check" CHECK ((change_type = ANY (ARRAY['create'::text, 'modify'::text, 'delete'::text]))) not valid;

alter table "public"."genome_history" validate constraint "genome_history_change_type_check";

alter table "public"."genome_history" add constraint "genome_history_genome_id_fkey" FOREIGN KEY (genome_id) REFERENCES genome(id) ON DELETE CASCADE not valid;

alter table "public"."genome_history" validate constraint "genome_history_genome_id_fkey";

alter table "public"."genome_history" add constraint "genome_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."genome_history" validate constraint "genome_history_user_id_fkey";

alter table "public"."protein_history" add constraint "protein_history_change_type_check" CHECK ((change_type = ANY (ARRAY['create'::text, 'modify'::text, 'delete'::text]))) not valid;

alter table "public"."protein_history" validate constraint "protein_history_change_type_check";

alter table "public"."protein_history" add constraint "protein_history_protein_id_fkey" FOREIGN KEY (protein_id) REFERENCES protein(id) ON DELETE CASCADE not valid;

alter table "public"."protein_history" validate constraint "protein_history_protein_id_fkey";

alter table "public"."protein_history" add constraint "protein_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."protein_history" validate constraint "protein_history_user_id_fkey";

alter table "public"."reaction_history" add constraint "reaction_history_change_type_check" CHECK ((change_type = ANY (ARRAY['create'::text, 'modify'::text, 'delete'::text]))) not valid;

alter table "public"."reaction_history" validate constraint "reaction_history_change_type_check";

alter table "public"."reaction_history" add constraint "reaction_history_reaction_id_fkey" FOREIGN KEY (reaction_id) REFERENCES reaction(id) ON DELETE CASCADE not valid;

alter table "public"."reaction_history" validate constraint "reaction_history_reaction_id_fkey";

alter table "public"."reaction_history" add constraint "reaction_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."reaction_history" validate constraint "reaction_history_user_id_fkey";

alter table "public"."species_history" add constraint "species_history_change_type_check" CHECK ((change_type = ANY (ARRAY['create'::text, 'modify'::text, 'delete'::text]))) not valid;

alter table "public"."species_history" validate constraint "species_history_change_type_check";

alter table "public"."species_history" add constraint "species_history_species_id_fkey" FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE not valid;

alter table "public"."species_history" validate constraint "species_history_species_id_fkey";

alter table "public"."species_history" add constraint "species_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."species_history" validate constraint "species_history_user_id_fkey";

create policy "Anyone can read genome history"
on "public"."genome_history"
as permissive
for select
to authenticated, anon
using (true);


create policy "Anyone can read protein history"
on "public"."protein_history"
as permissive
for select
to authenticated, anon
using (true);


create policy "Anyone can read reaction history"
on "public"."reaction_history"
as permissive
for select
to authenticated, anon
using (true);


create policy "Anyone can read species history"
on "public"."species_history"
as permissive
for select
to authenticated, anon
using (true);



