create table "public"."genome" (
    "id" bigint generated by default as identity not null,
    "strain_name" text,
    "sequence_bucket" text not null default 'genome_sequences'::text,
    "sequence_object" text,
    "species_id" bigint not null
);


alter table "public"."genome" enable row level security;

create table "public"."genome_synonym" (
    "source" text not null,
    "value" text not null,
    "genome_id" bigint not null
);


alter table "public"."genome_synonym" enable row level security;

alter table "public"."chemical" drop column "created_at";

alter table "public"."protein" drop column "created_at";

alter table "public"."reaction" drop column "created_at";

alter table "public"."species" drop column "created_at";

alter table "public"."species" drop column "display_options";

alter table "public"."synonym" drop column "created_at";

CREATE UNIQUE INDEX genome_pkey ON public.genome USING btree (id);

CREATE UNIQUE INDEX genome_synonym_pkey ON public.genome_synonym USING btree (genome_id, value, source);

CREATE INDEX genome_synonym_value_idx ON public.genome_synonym USING btree (value);

alter table "public"."genome" add constraint "genome_pkey" PRIMARY KEY using index "genome_pkey";

alter table "public"."genome_synonym" add constraint "genome_synonym_pkey" PRIMARY KEY using index "genome_synonym_pkey";

alter table "public"."genome" add constraint "genome_species_id_fkey" FOREIGN KEY (species_id) REFERENCES species(id) not valid;

alter table "public"."genome" validate constraint "genome_species_id_fkey";

alter table "public"."genome_synonym" add constraint "genome_synonym_genome_id_fkey" FOREIGN KEY (genome_id) REFERENCES genome(id) ON DELETE CASCADE not valid;

alter table "public"."genome_synonym" validate constraint "genome_synonym_genome_id_fkey";

create policy "Anyone can read genomes"
on "public"."genome"
as permissive
for select
to authenticated, anon
using (true);


create policy "Anyone can read genome synonyms"
on "public"."genome_synonym"
as permissive
for select
to authenticated, anon
using (true);



create policy "Anyone can read genome sequences"
on "storage"."objects"
as permissive
for select
to public
using ((bucket_id = 'genome_sequences'::text));



