create table "public"."graph" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp without time zone not null default now(),
    "user_id" uuid not null
);


alter table "public"."graph" enable row level security;

create table "public"."oauth2_connection" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "name" text not null,
    "access_token" text,
    "refresh_token" text,
    "expires_at" timestamp without time zone,
    "scope" text[] default '{}'::text[],
    "token_type" text,
    "needs_reconnect" boolean not null default false,
    "state" text
);


alter table "public"."oauth2_connection" enable row level security;

alter table "public"."node" add column "graph_id" bigint;

CREATE UNIQUE INDEX graph_pkey ON public.graph USING btree (id);

CREATE UNIQUE INDEX oauth2_connection_pkey ON public.oauth2_connection USING btree (id);

CREATE UNIQUE INDEX oauth2_connection_user_id_name_key ON public.oauth2_connection USING btree (user_id, name);

alter table "public"."graph" add constraint "graph_pkey" PRIMARY KEY using index "graph_pkey";

alter table "public"."oauth2_connection" add constraint "oauth2_connection_pkey" PRIMARY KEY using index "oauth2_connection_pkey";

alter table "public"."graph" add constraint "graph_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."graph" validate constraint "graph_user_id_fkey";

alter table "public"."node" add constraint "node_graph_id_fkey" FOREIGN KEY (graph_id) REFERENCES graph(id) ON DELETE CASCADE not valid;

alter table "public"."node" validate constraint "node_graph_id_fkey";

alter table "public"."oauth2_connection" add constraint "oauth2_connection_name_check" CHECK ((name = 'google'::text)) not valid;

alter table "public"."oauth2_connection" validate constraint "oauth2_connection_name_check";

alter table "public"."oauth2_connection" add constraint "oauth2_connection_token_type_check" CHECK ((token_type = 'Bearer'::text)) not valid;

alter table "public"."oauth2_connection" validate constraint "oauth2_connection_token_type_check";

alter table "public"."oauth2_connection" add constraint "oauth2_connection_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."oauth2_connection" validate constraint "oauth2_connection_user_id_fkey";

alter table "public"."oauth2_connection" add constraint "oauth2_connection_user_id_name_key" UNIQUE using index "oauth2_connection_user_id_name_key";

create policy "Authenticated user can manage their graphs"
on "public"."graph"
as permissive
for all
to public
using ((auth.uid() = user_id));



