create table "public"."synced_folder" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "user_id" uuid not null,
    "source" text not null,
    "remote_id" text not null
);


alter table "public"."synced_folder" enable row level security;

CREATE UNIQUE INDEX synced_folder_pkey ON public.synced_folder USING btree (id);

CREATE UNIQUE INDEX synced_folder_user_id_source_remote_id_key ON public.synced_folder USING btree (user_id, source, remote_id);

alter table "public"."synced_folder" add constraint "synced_folder_pkey" PRIMARY KEY using index "synced_folder_pkey";

alter table "public"."synced_folder" add constraint "synced_folder_source_check" CHECK ((source = 'google_drive'::text)) not valid;

alter table "public"."synced_folder" validate constraint "synced_folder_source_check";

alter table "public"."synced_folder" add constraint "synced_folder_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."synced_folder" validate constraint "synced_folder_user_id_fkey";

alter table "public"."synced_folder" add constraint "synced_folder_user_id_source_remote_id_key" UNIQUE using index "synced_folder_user_id_source_remote_id_key";

create policy "Authenticated users can manage their synced folders"
on "public"."synced_folder"
as permissive
for all
to public
using ((auth.uid() = user_id));



