create table "public"."chemical_history" (
    "id" bigint generated by default as identity not null,
    "time" timestamp without time zone,
    "chemical_id" bigint not null,
    "source" text not null,
    "source_details" text not null,
    "user_id" uuid,
    "change_type" text not null,
    "change_column" text
);


alter table "public"."chemical_history" enable row level security;

CREATE UNIQUE INDEX chemical_history_pkey ON public.chemical_history USING btree (id);

alter table "public"."chemical_history" add constraint "chemical_history_pkey" PRIMARY KEY using index "chemical_history_pkey";

alter table "public"."chemical_history" add constraint "chemical_history_change_type_check" CHECK ((change_type = ANY (ARRAY['create'::text, 'modify'::text, 'delete'::text]))) not valid;

alter table "public"."chemical_history" validate constraint "chemical_history_change_type_check";

alter table "public"."chemical_history" add constraint "chemical_history_chemical_id_fkey" FOREIGN KEY (chemical_id) REFERENCES chemical(id) ON DELETE CASCADE not valid;

alter table "public"."chemical_history" validate constraint "chemical_history_chemical_id_fkey";

alter table "public"."chemical_history" add constraint "chemical_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."chemical_history" validate constraint "chemical_history_user_id_fkey";

create policy "Anyone can read chemical history"
on "public"."chemical_history"
as permissive
for select
to authenticated, anon
using (true);



