create table "public"."project" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp without time zone not null default now(),
    "user_id" uuid not null
);


alter table "public"."project" enable row level security;

create table "public"."synced_file" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "user_id" uuid not null,
    "synced_folder_id" bigint not null,
    "is_folder" boolean not null default false,
    "parent_id" bigint,
    "source" text not null,
    "remote_id" text,
    "conflict_details" jsonb
);


alter table "public"."synced_file" enable row level security;

alter table "public"."file" add column "project_id" bigint;

alter table "public"."graph" add column "project_id" bigint;

alter table "public"."graph" alter column "user_id" drop not null;

alter table "public"."synced_folder" add column "project_id" bigint;

CREATE UNIQUE INDEX project_pkey ON public.project USING btree (id);

CREATE UNIQUE INDEX project_user_id_name_key ON public.project USING btree (user_id, name);

CREATE UNIQUE INDEX synced_file_pkey ON public.synced_file USING btree (id);

CREATE UNIQUE INDEX synced_file_user_id_source_remote_id_key ON public.synced_file USING btree (user_id, source, remote_id);

alter table "public"."project" add constraint "project_pkey" PRIMARY KEY using index "project_pkey";

alter table "public"."synced_file" add constraint "synced_file_pkey" PRIMARY KEY using index "synced_file_pkey";

alter table "public"."file" add constraint "file_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE not valid;

alter table "public"."file" validate constraint "file_project_id_fkey";

alter table "public"."graph" add constraint "graph_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE not valid;

alter table "public"."graph" validate constraint "graph_project_id_fkey";

alter table "public"."project" add constraint "project_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."project" validate constraint "project_user_id_fkey";

alter table "public"."project" add constraint "project_user_id_name_key" UNIQUE using index "project_user_id_name_key";

alter table "public"."synced_file" add constraint "synced_file_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES synced_file(id) ON DELETE CASCADE not valid;

alter table "public"."synced_file" validate constraint "synced_file_parent_id_fkey";

alter table "public"."synced_file" add constraint "synced_file_source_check" CHECK ((source = 'google_drive'::text)) not valid;

alter table "public"."synced_file" validate constraint "synced_file_source_check";

alter table "public"."synced_file" add constraint "synced_file_synced_folder_id_fkey" FOREIGN KEY (synced_folder_id) REFERENCES synced_folder(id) ON DELETE CASCADE not valid;

alter table "public"."synced_file" validate constraint "synced_file_synced_folder_id_fkey";

alter table "public"."synced_file" add constraint "synced_file_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."synced_file" validate constraint "synced_file_user_id_fkey";

alter table "public"."synced_file" add constraint "synced_file_user_id_source_remote_id_key" UNIQUE using index "synced_file_user_id_source_remote_id_key";

alter table "public"."synced_folder" add constraint "synced_folder_project_id_fkey" FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE not valid;

alter table "public"."synced_folder" validate constraint "synced_folder_project_id_fkey";

create policy "Authenticated user can manage their projects"
on "public"."project"
as permissive
for all
to public
using ((auth.uid() = user_id));


create policy "Authenticated users can manage their synced files"
on "public"."synced_file"
as permissive
for all
to public
using ((auth.uid() = user_id));



