drop trigger if exists "chemical_update_trigger" on "public"."chemical";

drop policy "Authenticated user can manage chemicals" on "public"."chemical";

drop policy "Authenticated user can create chemical_history" on "public"."chemical_history";

alter table "public"."profile" drop constraint "profile_id_fkey";

alter table "public"."user_role" drop constraint "user_role_user_id_fkey";

drop function if exists "public"."on_update_chemical"();

alter table "public"."profile" add constraint "profile_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_id_fkey";

alter table "public"."user_role" add constraint "user_role_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profile(id) ON DELETE CASCADE not valid;

alter table "public"."user_role" validate constraint "user_role_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
AS $function$
    SELECT EXISTS(
        SELECT user_id FROM public.user_role WHERE user_id = auth.uid() AND role = 'admin'
    );
$function$
;

CREATE OR REPLACE FUNCTION public.on_edit()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (current_user) = 'authenticated' THEN
        IF (TG_OP = 'INSERT') THEN
            EXECUTE format($$
                INSERT INTO public.%1$s_history
                    (time, %1$s_id, user_id, change_type, new_values)
                VALUES
                    (now(), $1.id, auth.uid(), 'create', to_jsonb($1));
            $$, TG_ARGV[0]) USING NEW; -- TG_ARGV[0] = table name
        ELSIF (TG_OP = 'UPDATE') THEN
            EXECUTE format($$
                INSERT INTO public.%1$s_history
                    (time, %1$s_id, user_id, change_type, new_values)
                VALUES
                    (now(), $1.id, auth.uid(), 'update', public.jsonb_diff_val(to_jsonb($1), to_jsonb($2)));
            $$, TG_ARGV[0]) USING NEW, OLD; -- TG_ARGV[0] = table name
        END IF;
    END IF;
    RETURN NULL; -- result is ignored since this is an AFTER trigger
END;
$function$
;

CREATE OR REPLACE FUNCTION public.jsonb_diff_val(val1 jsonb, val2 jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  result jsonb;
  v record;
BEGIN
   result = val1;
   FOR v IN SELECT * FROM jsonb_each(val2) LOOP
     IF result @> jsonb_build_object(v.key,v.value)
        THEN result = result - v.key;
     ELSIF result ? v.key THEN CONTINUE;
     ELSE
        result = result || jsonb_build_object(v.key, 'null');
     END IF;
   END LOOP;
   RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.node_setup(table_name text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    EXECUTE format($node_setup_format$
        -- RLS for main table
        ALTER TABLE public.%1$s ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Anyone can read %1$ss" ON public.%1$s FOR SELECT USING (true);
        CREATE POLICY "Admin can manage %1$ss" ON public.%1$s USING (public.is_admin());
        -- History table
        CREATE TABLE public.%1$s_history (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            time TIMESTAMP NOT NULL,
            %1$s_id BIGINT NOT NULL REFERENCES public.%1$s(id) ON DELETE CASCADE,
            source TEXT,
            source_details TEXT,
            user_id UUID REFERENCES public.profile(id),
            change_type TEXT NOT NULL CHECK (change_type IN ('create', 'update', 'delete')),
            new_values jsonb
        );
        -- RLS for history table
        ALTER TABLE IF EXISTS public.%1$s_history ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Anyone can read %1$s history" ON public.%1$s_history
            FOR SELECT USING (true);
        CREATE POLICY "Authenticated user can create their own %1$s history" ON public.%1$s_history
            FOR INSERT WITH CHECK (auth.uid() = user_id);

        CREATE TRIGGER %1$s_update_trigger
            AFTER INSERT OR UPDATE ON public.%1$s FOR EACH ROW
            EXECUTE PROCEDURE public.on_edit('%1$s');
    $node_setup_format$, table_name);
END;
$function$
;

create policy "Admin can manage chemicals"
on "public"."chemical"
as permissive
for all
to public
using (is_admin());


create policy "Authenticated user can create their own chemical history"
on "public"."chemical_history"
as permissive
for insert
to public
with check ((auth.uid() = user_id));


CREATE TRIGGER chemical_update_trigger AFTER INSERT OR UPDATE ON public.chemical FOR EACH ROW EXECUTE FUNCTION on_edit('chemical');


