create table "public"."file_data" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "synced_file_id" bigint,
    "file_id" bigint,
    "text_content" text
);


alter table "public"."file_data" enable row level security;

alter table "public"."synced_file" add column "processing_status" text;

CREATE UNIQUE INDEX file_data_pkey ON public.file_data USING btree (id);

alter table "public"."file_data" add constraint "file_data_pkey" PRIMARY KEY using index "file_data_pkey";

alter table "public"."file_data" add constraint "file_data_file_id_fkey" FOREIGN KEY (file_id) REFERENCES file(id) ON DELETE CASCADE not valid;

alter table "public"."file_data" validate constraint "file_data_file_id_fkey";

alter table "public"."file_data" add constraint "file_data_synced_file_id_fkey" FOREIGN KEY (synced_file_id) REFERENCES synced_file(id) ON DELETE CASCADE not valid;

alter table "public"."file_data" validate constraint "file_data_synced_file_id_fkey";

alter table "public"."file_data" add constraint "file_data_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."file_data" validate constraint "file_data_user_id_fkey";

alter table "public"."synced_file" add constraint "synced_file_processing_status_check" CHECK ((processing_status = ANY (ARRAY['not_started'::text, 'processing'::text, 'done'::text, 'error'::text]))) not valid;

alter table "public"."synced_file" validate constraint "synced_file_processing_status_check";

create policy "Authenticated users can manage their file data"
on "public"."file_data"
as permissive
for all
to public
using ((auth.uid() = user_id));



