-- task_links tracks tasks that are associated with a resource (table row). If a
-- row has a type, then we can enforce that only one task (or limited number of
-- tasks) can be running for that type at a time.
CREATE TABLE task_link(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- for RLS
    user_id uuid NOT NULL,
    -- only required if we want to enforce a limit on the number of concurrent
    -- tasks. The happens in the application layer.
    type text,
    -- celery task ID
    task_id text NOT NULL,
    -- time the task was created (submitted to the queue)
    task_created_at timestamptz NOT NULL DEFAULT (now() at time zone 'utc'),
    -- if the task is finished, it either succeeded or failed.
    task_finished_at timestamptz,
    -- if an error exists, then the task has failed.
    task_error text
);

ALTER TABLE task_link ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can manage their task links" ON task_link
    FOR ALL TO authenticated
        USING (auth.uid() = user_id);

ALTER publication supabase_realtime
    ADD TABLE task_link;

