-- task_links tracks tasks that are associated with a resource (table row). If a
-- row has a type, then we can enforce that only one task (or limited number of
-- tasks) can be running for that type at a time.
create table task_link (
    id bigint generated by default as identity primary key,
    -- for RLS
    user_id uuid not null,
    -- only required if we want to enforce a limit on the number of concurrent
    -- tasks. The happens in the application layer.
    type text,
    -- celery task ID
    task_id text not null,
    -- time the task was created (submitted to the queue)
    task_created_at timestamptz not null default (now() at time zone 'utc'),
    -- if the task is finished, it either succeeded or failed.
    task_finished_at timestamptz,
    -- if an error exists, then the task has failed.
    task_error text
);
alter table task_link enable row level security;
create policy "Authenticated users can manage their task links" on task_link
    for all to authenticated using (auth.uid() = user_id);
alter publication supabase_realtime add table task_link;
