-- TODO more reliable uploads
-- https://github.com/supabase/supabase/tree/master/examples/storage/resumable-upload-uppy

create policy "Anyone can read buckets"
    on storage.buckets for select
    to authenticated, anon
    using (true);

create policy "Authenticated user can create files"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'files');

-- create policy "Authenticated user can manage their own files"
--     on storage.objects for select
--     using (bucket_id = 'files' and (select requesting_user_id()) = owner_id);

create table file (
    id bigint generated by default as identity primary key,
    name text not null,
    size bigint not null,
    bucket_id text not null,
    object_path text not null,
    user_id text not null,
    mime_type text,
    latest_task_id text
);
alter table file enable row level security;
create policy "Authenticated user can manage their files" on file
  for all using (requesting_user_id() = user_id);
