create table tool (
    id bigint generated by default as identity primary key,
    name text not null,
    user_id text not null,
    unique (name, user_id)
);
alter table tool enable row level security;
create policy "Authenticated user can manage their tools" on tool
  for all using (requesting_user_id() = user_id);
