-- Create the set_updated_at function
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = current_timestamp;
    return new;
end;
$$ language plpgsql;

create table table_identification (
    id bigint generated by default as identity primary key,
    file_id text not null references file(id),
    user_id uuid not null,
    identifications jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (file_id)
);
alter table table_identification enable row level security;
create policy "Authenticated user can manage their table identifications" on table_identification
    for all to authenticated using (auth.uid()::uuid = user_id);

-- Add trigger to update updated_at
create trigger set_updated_at
    before update on table_identification
    for each row
    execute function public.set_updated_at();
