CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA extensions;
CREATE TABLE IF NOT EXISTS public.chemical (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    inchi VARCHAR(2000) UNIQUE NOT NULL,
    name TEXT,
    display_options JSONB,
    CONSTRAINT chemical_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.chemical ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS chemical_name_search_idx ON public.chemical USING GIN (name extensions.gin_trgm_ops);
CREATE POLICY "Anyone can read chemicals" ON public.chemical FOR
SELECT TO authenticated,
    anon USING (true);
