-- add species table

CREATE TABLE IF NOT EXISTS public.species
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT,
    display_options JSONB,
    CONSTRAINT species_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.species ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS species_name_search_idx ON public.species
    USING GIN (name extensions.gin_trgm_ops);

CREATE POLICY "Anyone can read species"
    ON public.species FOR SELECT
    TO authenticated, anon
    USING ( true );
