-- Chemicals

CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA extensions;
CREATE TABLE IF NOT EXISTS public.chemical (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    inchi VARCHAR(2000) NOT NULL,
    inchi_key TEXT UNIQUE NOT NULL,
    name TEXT,
    display_options JSONB,
    CONSTRAINT chemical_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.chemical ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS chemical_name_search_idx ON public.chemical USING GIN (name extensions.gin_trgm_ops);
CREATE POLICY "Anyone can read chemicals" ON public.chemical
    FOR SELECT USING (true);
CREATE POLICY "Authenticated user can manage chemicals" ON public.chemical
    TO authenticated USING (true);

CREATE TABLE public.chemical_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    chemical_id BIGINT NOT NULL REFERENCES public.chemical(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_details TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    change_type TEXT NOT NULL CHECK (change_type IN ('create', 'modify', 'delete')),
    change_column TEXT
);
ALTER TABLE IF EXISTS public.chemical_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read chemical history" ON public.chemical_history
    FOR SELECT USING (true);
CREATE POLICY "Authenticated user can manage chemical_history" ON public.chemical_history
    USING (auth.uid() = user_id);

-- Reactions

CREATE TABLE IF NOT EXISTS public.reaction (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    name TEXT,
    hash TEXT UNIQUE NOT NULL,
    display_options JSONB,
    CONSTRAINT reaction_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.reaction ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS reaction_name_search_idx ON public.reaction USING GIN (name extensions.gin_trgm_ops);
CREATE POLICY "Anyone can read reactions" ON public.reaction FOR
    SELECT TO authenticated, anon USING (true);

CREATE TABLE IF NOT EXISTS public.stoichiometry (
    chemical_id BIGINT NOT NULL REFERENCES public.chemical(id) ON DELETE CASCADE,
    reaction_id BIGINT NOT NULL REFERENCES public.reaction(id) ON DELETE CASCADE,
    coefficient DOUBLE PRECISION NOT NULL,
    compartment_rule TEXT,
    CONSTRAINT stoichiometry_pkey PRIMARY KEY (chemical_id, reaction_id)
);
ALTER TABLE IF EXISTS public.stoichiometry ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read stoichiometry" ON public.stoichiometry FOR
    SELECT TO authenticated, anon USING (true);

CREATE TABLE public.reaction_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    reaction_id BIGINT NOT NULL REFERENCES public.reaction(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_details TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    change_type TEXT NOT NULL CHECK (change_type IN ('create', 'modify', 'delete')),
    change_column TEXT
);
ALTER TABLE IF EXISTS public.reaction_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read reaction history" ON public.reaction_history FOR
    SELECT TO authenticated, anon USING (true);

-- Proteins

CREATE TABLE IF NOT EXISTS public.protein (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    short_name TEXT,
    sequence TEXT NOT NULL,
    CONSTRAINT protein_pkey PRIMARY KEY (id)
);
CREATE INDEX protein_name_search_idx ON public.protein
    USING GIN (name extensions.gin_trgm_ops);
CREATE INDEX protein_short_name_search_idx ON public.protein
    USING GIN (short_name extensions.gin_trgm_ops);

ALTER TABLE IF EXISTS public.protein ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read proteins" ON public.protein
    FOR SELECT TO authenticated, anon USING (true);

CREATE TABLE IF NOT EXISTS public.protein_reaction (
    protein_id BIGINT NOT NULL REFERENCES public.protein(id) ON DELETE CASCADE,
    reaction_id BIGINT NOT NULL REFERENCES public.reaction(id) ON DELETE CASCADE,
    constraint protein_reaction_pkey PRIMARY KEY (protein_id, reaction_id)
);

ALTER TABLE IF EXISTS public.protein_reaction ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read protein-reaction" ON public.protein_reaction
    FOR SELECT TO authenticated, anon USING (true);

CREATE TABLE public.protein_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    protein_id BIGINT NOT NULL REFERENCES public.protein(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_details TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    change_type TEXT NOT NULL CHECK (change_type IN ('create', 'modify', 'delete')),
    change_column TEXT
);
ALTER TABLE IF EXISTS public.protein_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read protein history" ON public.protein_history FOR
    SELECT TO authenticated, anon USING (true);

-- Species

CREATE TABLE IF NOT EXISTS public.species (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    name TEXT,
    rank TEXT,
    CONSTRAINT species_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS species_name_search_idx ON public.species USING GIN (name extensions.gin_trgm_ops);

ALTER TABLE IF EXISTS public.species ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read species" ON public.species FOR
SELECT TO authenticated,
    anon USING (true);
CREATE POLICY "Authenticated user can write species" ON public.species FOR
    INSERT TO authenticated WITH CHECK (true);

CREATE TABLE public.species_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    species_id BIGINT NOT NULL REFERENCES public.species(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_details TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    change_type TEXT NOT NULL CHECK (change_type IN ('create', 'modify', 'delete')),
    change_column TEXT
);
ALTER TABLE IF EXISTS public.species_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read species history" ON public.species_history FOR
    SELECT TO authenticated, anon USING (true);

-- Synonyms

CREATE TABLE public.synonym
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    source TEXT NOT NULL,
    value TEXT NOT NULL,
    chemical_id BIGINT REFERENCES public.chemical(id) ON DELETE CASCADE,
    reaction_id BIGINT REFERENCES public.reaction(id) ON DELETE CASCADE,
    protein_id BIGINT REFERENCES public.protein(id) ON DELETE CASCADE,
    species_id BIGINT REFERENCES public.species(id) ON DELETE CASCADE,
    CONSTRAINT synonym_pkey PRIMARY KEY (id),
    UNIQUE (chemical_id, value, source),
    UNIQUE (reaction_id, value, source),
    UNIQUE (protein_id, value, source),
    UNIQUE (species_id, value, source)
);
CREATE INDEX synonym_value_idx ON public.synonym (value);

ALTER TABLE IF EXISTS public.synonym ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read synonyms"
    ON public.synonym FOR SELECT
    TO authenticated, anon
    USING ( true );

-- Genomes
-- i.e. strain, for now

CREATE TABLE public.genome (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    strain_name TEXT,
    bucket TEXT NOT NULL DEFAULT 'genome_sequences',
    genbank_gz_object TEXT,
    genbank_gz_file_size_bytes BIGINT,
    species_id BIGINT NOT NULL REFERENCES public.species(id)
);
ALTER TABLE public.genome ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read genomes"
    ON public.genome FOR SELECT TO authenticated, anon USING ( true );

CREATE TABLE public.genome_synonym (
    source TEXT NOT NULL,
    value TEXT NOT NULL,
    genome_id BIGINT NOT NULL REFERENCES public.genome(id) ON DELETE CASCADE,
    CONSTRAINT genome_synonym_pkey PRIMARY KEY (genome_id, value, source)
);
CREATE INDEX genome_synonym_value_idx ON public.genome_synonym (value);
ALTER TABLE public.genome_synonym ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read genome synonyms"
    ON public.genome_synonym FOR SELECT TO authenticated, anon USING ( true );

CREATE TABLE public.genome_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time TIMESTAMP,
    genome_id BIGINT NOT NULL REFERENCES public.genome(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_details TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    change_type TEXT NOT NULL CHECK (change_type IN ('create', 'modify', 'delete')),
    change_column TEXT
);
ALTER TABLE IF EXISTS public.genome_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read genome history" ON public.genome_history FOR
    SELECT TO authenticated, anon USING (true);
