CREATE TABLE IF NOT EXISTS public.reaction (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT,
    display_options JSONB,
    CONSTRAINT reaction_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.reaction ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS reaction_name_search_idx ON public.reaction USING GIN (name extensions.gin_trgm_ops);
CREATE POLICY "Anyone can read reactions" ON public.reaction FOR
SELECT TO authenticated,
    anon USING (true);
