-- add config to get a list of tables

CREATE TABLE IF NOT EXISTS public.display_config
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    config JSONB,
    CONSTRAINT display_config_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.display_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read display_config"
    ON public.display_config FOR SELECT
    TO authenticated, anon
    USING ( true );
