CREATE TABLE IF NOT EXISTS public.synonym
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    source text NOT NULL,
    value text NOT NULL,
    chemical_id bigint NOT NULL REFERENCES public.chemical(id) ON DELETE CASCADE,
    CONSTRAINT synonym_pkey PRIMARY KEY (id),
    UNIQUE (source, value)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.synonym
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.synonym
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.synonym TO anon;

GRANT ALL ON TABLE public.synonym TO postgres;

GRANT ALL ON TABLE public.synonym TO supabase_admin;

GRANT ALL ON TABLE public.synonym TO authenticated;

GRANT ALL ON TABLE public.synonym TO service_role;
