CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA "extensions";

-- articles

CREATE TABLE public.article (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    authors JSONB NOT NULL,
    doi TEXT NOT NULL,
    journal TEXT,
    user_id UUID REFERENCES public.user(id) NOT NULL,
    public BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (user_id, doi)
);
ALTER TABLE IF EXISTS public.article ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated user can manage their articles" ON public.article
    FOR ALL USING (auth.uid() = user_id);

-- CREATE TABLE public.article_content (
--     article_id BIGINT NOT NULL REFERENCES public.article(id),
--     chunk INT NOT NULL,
--     text TEXT NOT NULL,
--     embedding vector(1536) NOT NULL,
--     CONSTRAINT article_content_pkey PRIMARY KEY (chunk, article_id)
-- );
-- ALTER TABLE IF EXISTS public.article ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Authenticated user can manage their article content" ON public.article
--     FOR ALL USING (auth.uid() = user_id);
