create extension pg_jsonschema;

-- Node Types

create table node_type (
  id text primary key,
  icon text,
  list_definition_ids text[] not null,
  detail_definition_ids text[] not null,
  options jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object",
    "properties": {
      "joinLimits": {
        "patternProperties": {
          "^[a-zA-Z0-9_]+$": {"type": "integer"}
        }
      }
    }
  }', options))
);
alter table node_type enable row level security;
create policy "Anyone can read node types" on node_type for select using (true);

-- Property definitions & components

create table definition (
  id text primary key,
  component_id text not null,
  options jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object",
    "properties": {
      "bucket": {"type": "string"},
      "bucketKey": {"type": "string"},
      "buttonText": {"type": "string"},
      "dataKey": {"type": "string"},
      "displayName": {"type": "string"},
      "gridSize": {"type": "number"},
      "height": {"type": "number"},
      "linkTemplate": {"type": "string"},
      "nameKey": {"type": "string"},
      "pathTemplate": {"type": "string"},
      "sizeKeyBytes": {"type": "string"},
      "width": {"type": "number"},
      "optionsTable": {
        "type": "object",
        "patternProperties": {
          "^[a-zA-Z0-9_]+$": {
            "type": "object",
            "properties": {
              "nameKey": {"type": "string"},
              "linkTemplate": {"type": "string"}
            }
          }
        }
      }
    }
  }', options))
);
alter table definition enable row level security;
create policy "Anyone can read property definitions" on definition for select using (true);

-- Nodes

create table node (
  id bigint primary key generated by default as identity,
  node_type_id text references node_type(id) not null,
  user_id uuid references auth.users(id),
  data jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object"
  }', data)),
  -- Used to determine unique nodes in a node-type-specific way
  hash text unique not null
);
alter table node enable row level security;
create policy "Anyone can read nodes" on node for select using (true);
create policy "Authenticated user can manage their nodes" on node for all using (auth.uid() = user_id);

-- Node History

create table node_history (
    id bigint primary key generated by default as identity,
    time timestamp,
    node_id bigint not null references node(id) on delete cascade,
    source text not null,
    source_details text not null,
    user_id uuid references auth.users(id),
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);
alter table node_history enable row level security;
create policy "Anyone can read node_history" on node_history for select using (true);

-- Edges

create table edge (
  id bigint primary key generated by default as identity,
  source bigint references node(id) not null,
  destination bigint references node(id) not null,
  user_id uuid references auth.users(id),
  data jsonb
);
alter table edge enable row level security;
create policy "Anyone can read edges" on edge for select using (true);
create policy "Authenticated user can manage their edges" on edge for all using (auth.uid() = user_id);

-- Edge History

create table edge_history (
    id bigint primary key generated by default as identity,
    time timestamp,
    edge_id bigint not null references edge(id) on delete cascade,
    source text not null,
    source_details text not null,
    user_id uuid references auth.users(id),
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);
alter table edge_history enable row level security;
create policy "Anyone can read edge_history" on edge_history for select using (true);
-- TODO how to join to edge.public? probably create edge_history_public as a
-- materialized view. for now we'll make everything public

-- For later

-- https://tech.ingrid.com/sql-as-graph-database/
-- WITH RECURSIVE traverse(node_id, entity_type, entity_id) AS (
--     SELECT
--         node_id,
--         entity_type,
--         entity_id
--     FROM
--         entity
--     WHERE
--         entity.entity_id = $1 AND
--         entity.entity_type = 'tracking_number'
--     UNION ALL
--     SELECT
--         entity.node_id,
--         entity.entity_type,
--         entity.entity_id
--     FROM traverse JOIN
--     relation ON traverse.node_id = relation.child JOIN
--     entity ON relation.parent = entity.node_id
-- )
-- SELECT
--     traverse.entity_id as order_id
-- FROM traverse
-- WHERE traverse.entity_type = 'order'
-- GROUP BY traverse.entity_id
-- ORDER BY traverse.entity_id ASC
-- LIMIT $2;
--
-- Also: https://www.dylanpaulus.com/posts/postgres-is-a-graph-database/
--
-- https://news.ycombinator.com/item?id=35386948
--
-- https://www.alibabacloud.com/blog/postgresql-graph-search-practices---10-billion-scale-graph-with-millisecond-response_595039
--
-- and THEN switch to EdgeDB, AGE, Postgres+GQL, or Neo4j
