-- Projects

-- Projects are owned by users and referenced by graphs, files, and synced
-- folders

create table project (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default (now() at time zone 'utc'),
    user_id uuid not null references auth.users(id) on delete cascade,
    -- TODO implement organizations
    -- organization_id bigint references organization(id) on delete cascade,
    unique (user_id, name)
);
alter table project enable row level security;
create policy "Authenticated user can manage their projects" on project
  for all using (auth.uid() = user_id);

-- Set up new users with default project & profile
create function public.handle_new_user() returns trigger
  security definer
as $$
begin
  insert into public.profile (id)
    values (new.id);

  insert into public.project (name, user_id)
    values ('default', new.id);

  return new;
end;
$$ language plpgsql;

-- Trigger to execute the function after a new user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
