create table oauth2_connection (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null check (name in ('google')),
    access_token text,
    refresh_token text,
    expires_at timestamp,
    scope text[] default '{}',
    token_type text check (token_type in ('Bearer')),
    -- e.g. if the user has revoked access to the app or the refresh token has expired
    needs_reconnect boolean not null default false,
    -- random string to prevent CSRF
    state text,
    unique (user_id, name)
);
-- only service account can access this table
alter table oauth2_connection enable row level security;
