-- task_links tracks tasks that are associated with a resource (table row). If a
-- row has a type, then we can enforce that only one task (or limited number of
-- tasks) can be running for that type at a time.
create table task_link (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id),
    -- only required if we want to enforce a limit on the number of concurrent
    -- tasks. The happens in the application layer.
    type text,
    -- celery task ID
    task_id text,
    -- TODO is this when we submit the task?
    task_created_at timestamp,
    -- if the task is finished, it either succeeded or failed.
    task_finished_at timestamp,
    -- if an error exists, then the task has failed.
    task_error text
);
alter table task_link enable row level security;
create policy "Authenticated users can manage their task links" on task_link
    for all using (auth.uid() = user_id);
