CREATE TABLE IF NOT EXISTS public.protein (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT,
    CONSTRAINT protein_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.protein ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS protein_name_search_idx ON public.protein
    USING GIN (name extensions.gin_trgm_ops);
CREATE POLICY "Anyone can read proteins" ON public.protein
    FOR SELECT TO authenticated, anon USING (true);

CREATE TABLE IF NOT EXISTS public.protein_reaction (
    protein_id BIGINT NOT NULL REFERENCES public.protein(id) ON DELETE CASCADE,
    reaction_id BIGINT NOT NULL REFERENCES public.reaction(id) ON DELETE CASCADE,
    constraint protein_reaction_pkey PRIMARY KEY (protein_id, reaction_id)
);
ALTER TABLE IF EXISTS public.protein_reaction ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read protein-reaction" ON public.protein_reaction
    FOR SELECT TO authenticated, anon USING (true);
