create extension pg_jsonschema;

-- Graphs

-- Graphs are owned by users and referenced by nodes

create table graph (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default (now() at time zone 'utc'),
    user_id uuid references auth.users(id) on delete cascade,
    project_id bigint not null references project(id) on delete cascade
);
alter table graph enable row level security;
create policy "Authenticated user can manage their graphs" on graph
  for all using (auth.uid() = user_id);

-- -- TODO implement roles by permissions with organizations and teams
-- -- https://github.com/orgs/supabase/discussions/811
-- -- if slow, maybe use a materialized view
-- create table graph_roles (
--     id bigint generated by default as identity primary key,
--     graph_id bigint not null references graph(id) on delete cascade,
--     user_id uuid not null references auth.users(id) on delete cascade,
--     -- TODO inherit roles as well
--     role text not null check (role in ('admin', 'editor', 'viewer')),
--     unique (graph_id, user_id)
-- );

-- Node Types

create table node_type (
  id text primary key,
  icon text,
  top_level boolean not null default false,
  list_definition_ids text[] not null,
  detail_definition_ids text[] not null,
  options jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object",
    "properties": {
      "joinLimits": {
        "patternProperties": {
          "^[a-zA-Z0-9_]+$": {"type": "integer"}
        }
      }
    }
  }', options))
);
alter table node_type enable row level security;
create policy "Anyone can read node types" on node_type for select using (true);

-- Property definitions & components

create table definition (
  id text primary key,
  component_id text not null,
  options jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object",
    "properties": {
      "bucket": {"type": "string"},
      "bucketKey": {"type": "string"},
      "buttonText": {"type": "string"},
      "dataKey": {"type": "string"},
      "displayName": {"type": "string"},
      "gridSize": {"type": "number"},
      "height": {"type": "number"},
      "linkTemplate": {"type": "string"},
      "nameTemplate": {"type": "string"},
      "pathTemplate": {"type": "string"},
      "sizeKeyBytes": {"type": "string"},
      "width": {"type": "number"},
      "optionsTable": {
        "type": "object",
        "patternProperties": {
          "^[a-zA-Z0-9_]+$": {
            "type": "object",
            "properties": {
              "nameKey": {"type": "string"},
              "linkTemplate": {"type": "string"}
            },
            "additionalProperties": false
          }
        }
      }
    },
    "additionalProperties": false
  }', options))
);
alter table definition enable row level security;
create policy "Anyone can read property definitions" on definition for select using (true);

-- Nodes

create table node (
  id bigint primary key generated by default as identity,
  node_type_id text references node_type(id) not null,
  graph_id bigint references graph(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  data jsonb not null default '{}',
  check (jsonb_matches_schema('{
    "type": "object"
  }', data)),
  -- Used to determine unique nodes in a node-type-specific way
  hash text unique not null
);
create index node_node_type_id_idx on node (node_type_id);

alter table node enable row level security;
create policy "Anyone can read nodes" on node for select using (true);
create policy "Authenticated user can manage their nodes" on node for all using (auth.uid() = user_id);

-- Node History

create table node_history (
    id bigint primary key generated by default as identity,
    time timestamptz,
    node_id bigint not null references node(id) on delete cascade,
    source text not null,
    source_details text not null,
    user_id uuid references auth.users(id) on delete cascade,
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);
create index node_history_node_id_idx on node_history (node_id);

alter table node_history enable row level security;
create policy "Anyone can read node_history" on node_history for select using (true);

-- Edges

create table edge (
  id bigint primary key generated by default as identity,
  source_id bigint references node(id) on delete cascade not null,
  destination_id bigint references node(id) on delete cascade not null,
  relationship text not null,
  user_id uuid references auth.users(id) on delete cascade,
  data jsonb,
  hash text unique not null
);
create index edge_source_id_idx on edge (source_id);
create index edge_destination_id_idx on edge (destination_id);

alter table edge enable row level security;
create policy "Anyone can read edges" on edge for select using (true);
create policy "Authenticated user can manage their edges" on edge for all using (auth.uid() = user_id);

-- Edge History

create table edge_history (
    id bigint primary key generated by default as identity,
    time timestamptz,
    edge_id bigint not null references edge(id) on delete cascade,
    source text not null,
    source_details text not null,
    user_id uuid references auth.users(id),
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);

create index edge_history_edge_id_idx on edge_history (edge_id);

alter table edge_history enable row level security;
create policy "Anyone can read edge_history" on edge_history for select using (true);
-- TODO how to join to edge.public? probably create edge_history_public as a
-- materialized view. for now we'll make everything public

-- Search views

-- TODO this doesn't support RLS, but by the time we need secure search, we'll
-- probably need a real search engine
create materialized view node_search as
  (select
    node.id,
    node.node_type_id,
    node.data->>'name' as name,
    node.data->>'name' as value,
    'Name' as source
  from node
    where node.data->>'name' is not null)
union all
  (select
    node1.id,
    node1.node_type_id,
    node1.data->>'name' as name,
    node2.data->>'value' as value,
    node2.data->>'source' as source
  from node as node1
    join edge on edge.source_id = node1.id
    join node as node2 on edge.destination_id = node2.id
    where node2.node_type_id = 'synonym' and node2.data->>'value' is not null);
create index node_search_value_idx on node_search using gin (value gin_trgm_ops);
create index node_search_value_exact_idx on node_search (value);

-- For later

-- https://tech.ingrid.com/sql-as-graph-database/
-- WITH RECURSIVE traverse(node_id, entity_type, entity_id) AS (
--     SELECT
--         node_id,
--         entity_type,
--         entity_id
--     FROM
--         entity
--     WHERE
--         entity.entity_id = $1 AND
--         entity.entity_type = 'tracking_number'
--     UNION ALL
--     SELECT
--         entity.node_id,
--         entity.entity_type,
--         entity.entity_id
--     FROM traverse JOIN
--     relation ON traverse.node_id = relation.child JOIN
--     entity ON relation.parent = entity.node_id
-- )
-- SELECT
--     traverse.entity_id as order_id
-- FROM traverse
-- WHERE traverse.entity_type = 'order'
-- GROUP BY traverse.entity_id
-- ORDER BY traverse.entity_id ASC
-- LIMIT $2;
--
-- Also: https://www.dylanpaulus.com/posts/postgres-is-a-graph-database/
--
-- https://news.ycombinator.com/item?id=35386948
--
-- https://www.alibabacloud.com/blog/postgresql-graph-search-practices---10-billion-scale-graph-with-millisecond-response_595039
--
-- and THEN switch to EdgeDB, AGE, Postgres+GQL, or Neo4j
