create table oauth2_connection (
    id bigint generated by default as identity primary key,
    -- TODO use an "owner" table to prepare for organizations
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null check (name in ('google')),
    access_token text,
    refresh_token text,
    expires_at timestamp,
    scope text[] default '{}',
    token_type text check (token_type in ('Bearer')),
    -- e.g. if the user has revoked access to the app or the refresh token has expired
    needs_reconnect boolean not null default false,
    -- random string to prevent CSRF
    state text,
    unique (user_id, name)
);
-- only service account can access this table
alter table oauth2_connection enable row level security;

create table synced_folder (
    id bigint generated by default as identity primary key,
    name text not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    -- null poject_id indicates the default project
    project_id bigint references project(id) on delete cascade,
    source text not null check (source in ('google_drive')),
    -- the folder id in the remote service
    remote_id text not null,
    -- processing status
    update_task_id text,
    update_task_error text,
    update_task_created_at timestamp,
    unique (user_id, source, remote_id)
);
alter table synced_folder enable row level security;
create policy "Authenticated users can manage their synced folders" on synced_folder
    for all using (auth.uid() = user_id);
alter publication supabase_realtime add table synced_folder;

create table synced_file (
    id bigint generated by default as identity primary key,
    name text not null,
    mime_type text not null,
    user_id uuid not null references auth.users(id) on delete cascade,
    synced_folder_id bigint not null references synced_folder(id) on delete cascade,
    is_folder boolean not null default false,
    -- if the parent is the synced folder, then use -1, i.e. root
    parent_ids bigint[] not null default '{}',
    source text not null check (source in ('google_drive')),
    -- the file id in the remote service. Null in the case of a sync conflict.
    -- Details will be in conflict_details.
    remote_id text,
    conflict_details jsonb,
    unique (user_id, source, remote_id),
    processing_status text check (processing_status in ('not_started', 'processing', 'done', 'error')),
    -- when the remote file has been deleted
    deleted boolean not null default false
);
alter table synced_file enable row level security;
create policy "Authenticated users can manage their synced files" on synced_file
    for all using (auth.uid() = user_id);
alter publication supabase_realtime add table synced_file;

-- data about the file including contents and annotations
create table file_data (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    -- can only be a synced file for now
    synced_file_id bigint not null references synced_file(id) on delete cascade,
    -- text extract that can be searched or passed to LLM
    text_content text,
    -- a shorter LLM-generated summary
    text_summary text
);
alter table file_data enable row level security;
create policy "Authenticated users can manage their file data" on file_data
    for all using (auth.uid() = user_id);
alter publication supabase_realtime add table file_data;
