-- This could replace the tables in _graph.sql

-- The tables in _tables.sql etc. could be replaced by this new approach plus
-- some data loading scripts that create the actual tables, resource types, etc.

-- a `dataset` is a postgres table created by a user, usually from a CSV or
-- other file. The user populates it and queries it. Example:
-- create table dataset_<user_uuid>_<dataset_id> (
--     id bigint primary key generated by default as identity,
--     < user defined columns >
-- );

-- Datasets are connected through foreign keys and through dataset junction
-- tables (DJT). DJTs are directed and, when they represent a graph edge, they
-- also have a data payload. They are designed to support PostgREST resource embedding.
-- An example:
-- create table djt_<user_uuid>_<dataset_id>__<user_uuid>_<dataset_id> (
--   id bigint primary key generated by default as identity,
--   source_id bigint references dataset_<user_uuid>_<dataset_id>(id),
--   destination_id bigint references dataset_<user_uuid>_<dataset_id>(id),
--   data jsonb
-- );

-- `dataset_metadata` is a table that stores metadata about the dataset, such as
-- the number of rows, the size on disk, the last time it was updated, etc. It
-- is not generally queried by the user.

-- synced_file has 1:many optional relationship with dataset_metadata. a dataset
-- is the "raw" import of a file, so only one file per dataset. (but those files
-- might not be SyncedFile instances. could be a file upload, etc.) One
-- synced_file can generate multiple datasets.

create table dataset_metadata (
    id bigint primary key generated by default as identity,
    user_id uuid not null references auth.users(id),
    project text not null default 'default',
    name text not null,
    -- table in the `data` schema
    table_name text not null,
    schema_name text not null,
    -- - i'm giving up on soft deletes! If users want to "undo" a change, make
    --   them do it the slow way (i.e. contact support).
    -- - Give them lots of warning before deletions. Keep explicit history for
    --   them whenever there is automatic updates (e.g. for file syncs) and make
    --   the history queryable (and by extension, recoverable).
    -- - When to cascade delete? Whenever a user deletes something where it's
    --   intuitive to have a cascade.
    --   + Not in the general case. For users we don't cascade because it's an
    --     enormous operation so needs to be done as a job.
    -- - Hard deletes make unique contstraints way more powerful, e.g. guarantee
    --   namespaces at the database level.
    sync_folder_task_link_id bigint references task_link(id),
    unique (user_id, project, name)
);
alter table dataset_metadata enable row level security;
create policy "Authenticated users can manage their dataset metadata" on dataset_metadata
    for all using (auth.uid() = user_id);

-- TODO
-- https://supabase.com/docs/guides/database/postgres/row-level-security#rls-performance-recommendations
create table synced_file_dataset_metadata (
    id bigint generated by default as identity,
    synced_file_id bigint not null references synced_file(id),
    dataset_metadata_id bigint not null references dataset_metadata(id) on delete cascade,
    user_id uuid not null references auth.users(id),
    last_processed_version text,
    has_unprocessed_version boolean not null default true,
    -- join table needs both external references in the primary key to be
    -- detected by postgrest
    sync_file_to_dataset_task_link_id bigint references task_link(id),
    primary key (id, synced_file_id, dataset_metadata_id)
);
alter table synced_file_dataset_metadata enable row level security;
create policy "Authenticated users can manage their synced file dataset sync" on synced_file_dataset_metadata
    for all using (auth.uid() = user_id);

-- TODO can any of these be queried directly from the dataset/djt history?
-- assuming we use a model like https://wiki.postgresql.org/images/6/64/Fosdem20150130PostgresqlTemporal.pdf
create table dataset_history_metadata (
    id bigint primary key generated by default as identity,
    user_id uuid references auth.users(id),
    time timestamptz, -- do not assume that this is a unique identifier for the change
    dataset_table_name text not null,
    dataset_row_id bigint not null,
    source text not null,
    source_details text not null,
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);
alter table dataset_history_metadata enable row level security;
create policy "Authenticated users can manage their dataset history metadata" on dataset_history_metadata
    for all using (auth.uid() = user_id);

-- TODO can any of these be queried directly from the dataset/djt history?
-- assuming we use a model like https://wiki.postgresql.org/images/6/64/Fosdem20150130PostgresqlTemporal.pdf
create table djt_history_metadata (
    id bigint primary key generated by default as identity,
    user_id uuid references auth.users(id),
    time timestamptz, -- do not assume that this is a unique identifier for the change
    djt_table_name text not null,
    djt_row_id bigint not null,
    source text not null,
    source_details text not null,
    change_type text not null check (change_type IN ('create', 'modify', 'delete')),
    change_column text
);
alter table djt_history_metadata enable row level security;
create policy "Authenticated users can manage their djt history metadata" on djt_history_metadata
    for all using (auth.uid() = user_id);

-- TODO how to share across projects? Is this an "extension"?
create table resource_type (
    id bigint primary key generated by default as identity
);
alter table resource_type enable row level security;
create policy "All users can view resource types" on resource_type
    for select using (true);
