-- custom tables live in a separate schema. among other things, this allows
-- helps avoid challenges with supabase type generation & database diffing

-- This example private schema uses postgrest follow-privileges to ensure that
-- personal api definitions are not leaked to other users.

-- updating this function will update the schemas immediately! see:
-- https://postgrest.org/en/v12/references/configuration.html#in-database-configuration
create schema postgrest;
grant usage on schema postgrest to authenticator;
create or replace function postgrest.pre_config()
returns void as $$
  select
      set_config('pgrst.db_schemas', 'public,storage,graphql_public,data_example', true)
$$ language sql;
-- the prod version of this function is to hit the meta api. does that work in
-- dev too?

-- schemas for users will be data_<user_id> and will have the same permissions
-- as this example schema
create schema data_example;
create table data_example.permission_check (
  id serial primary key
);
-- with this, anon can see the table in openapi when openapi_mode is set to
-- ignore-privileges (not follow-priviliges):
grant usage on schema data_example to anon;
-- with this, anon can see the table in openapi when openapi_mode is set to
-- follow-privileges:
grant select on data_example.permission_check to anon;

-- Update PostgREST settings for multi-schema support
-- see: https://github.com/orgs/supabase/discussions/12270
-- Restrict access to the OpenAPI spec to users who need it
ALTER ROLE authenticator SET pgrst.openapi_mode TO "follow-privileges";
-- Add additional schemas to the PostgREST configuration
ALTER ROLE authenticator SET pgrst.db_schemas TO "public,storage,graphql_public,data_example";
NOTIFY pgrst, 'reload config';
NOTIFY pgrst, 'reload schema'; -- needed if you update the schema during testing


-- ----------
-- more notes
-- ----------

-- Goal: each user gets their own schema
-- Reason: to keep the super nice auto REST auto GraphQL but not leak any schema
-- info to other users
-- Test:
-- + separate JWT validation for openapi/postgrest on each schema
--   - can test using the following data_for_user schema
--   - is this possible just by setting a config?
--     https://postgrest.org/en/v12/references/configuration.html#openapi-mode
--   - could disable openapi spec
--     https://github.com/orgs/supabase/discussions/9464 and
--     https://github.com/orgs/supabase/discussions/4547#discussioncomment-3487883
--   - the above does not feel reliable at all. doesn't work locally
--   - maybe ... for local dev need PGRST_OPENAPI_MODE in postgrest container
--     ... try in a post-supabase-start command, re-running the docker container
--         https://stackoverflow.com/questions/27812548/how-to-set-an-environment-variable-in-a-running-docker-container
--     w a new env var ()
-- + run pg_graphql on a schema that is not public
-- + separate JWT validation for pg_graphql on each schema
-- + test the schemas running in separate databases & regions
-- [ ]  go back and test out the local setup _without_ follow privileges
-- Implement:
-- + API gateway to handle api keys for user access
-- + Proxy (same API Gateway? python API?) for frontend to access the schemas
-- Issues:
-- + supabase is not going to run multiple postgrest servers for us

-- create schema data_for_user;
-- grant usage on schema data_for_user to service_role;
-- grant all on all tables in schema data_for_user to service_role;
-- grant all on all routines in schema data_for_user to service_role;
-- grant all on all sequences in schema data_for_user to service_role;
-- alter default privileges for role postgres in schema data_for_user grant all on tables to service_role;
-- alter default privileges for role postgres in schema data_for_user grant all on routines to service_role;
-- alter default privileges for role postgres in schema data_for_user grant all on sequences to service_role;

-- create table data_for_user.test (
--     id bigint primary key generated by default as identity
-- );
-- -- This grant also causes the table to be visible in the public schema
-- -- grant all on all tables in schema data_for_user to anon;

