name: PGTap Tests
on:
  push:
    paths:
    - 'supabase/migrations/**'
    - '.github/workflows/pgtap.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db
