name: Run tests
on:
  push:
    paths:
      - "supabase/migrations/**"
      - "backend/**"
      - ".github/workflows/tests.yml"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.142.2
      - name: Supabase Start
        run: supabase start
      - name: Run DB Tests
        run: supabase test db
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
        with:
          version: 1.4.0
      - name: Install backend depencencies
        working-directory: backend/
        run: poetry install --no-interaction
      - name: Run backend tests
        working-directory: backend/
        run: poetry run pytest
        env:
          POSTGRESQL_CONNECTION_STRING: "postgresql+asyncpg://postgres:postgres@localhost:54322/postgres"
          REDIS_CONNECTION_STRING: redis://localhost:6379
